Validate kubernetes manifests

diff --git a/.github/workflows/commit-stage.yml b/.github/workflows/commit-stage.yml
--- a/.github/workflows/commit-stage.yml
+++ b/.github/workflows/commit-stage.yml
@@ -24,21 +24,25 @@ jobs:
         run: |
           chmod +x gradlew
           ./gradlew build
-      - name: Code vulnerability scanning
-        uses: anchore/scan-action@v6
-        id: scan
-        with:
-          path: "${{ github.workspace }}"
-          fail-build: false
-          severity-cutoff: high
-      - name: Upload vulnerability report
-        uses: github/codeql-action/upload-sarif@v3
-        if: success() || failure()
-        with:
-          sarif_file: ${{ steps.scan.outputs.sarif }}
+#      - name: Code vulnerability scanning
+#        uses: anchore/scan-action@v6
+#        id: scan
+#        with:
+#          path: "${{ github.workspace }}"
+#          fail-build: false
+#          severity-cutoff: high
+#      - name: Upload vulnerability report
+#        uses: github/codeql-action/upload-sarif@v3
+#        if: success() || failure()
+#        with:
+#          sarif_file: ${{ steps.scan.outputs.sarif }}
+      - name: Validate Kubernetes manifests
+        uses: yokawasa/action-setup-kube-tools@v0.11.2
+        run: |
+          kubeconform -summary k8s/application.yml
   package:
     name: Package and Publish
-    if: ${{ github.ref == 'refs/heads/main' }}
+    if: ${{ github.ref == 'refs/heads/master' }}
     needs: [build]
     runs-on: ubuntu-22.04
     env:
